"""Initial migration.

Revision ID: 7cef11fd323a
Revises: 
Create Date: 2022-01-05 01:04:22.234175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cef11fd323a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('account_type_change_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('wanted_type', sa.Integer(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=True),
    sa.Column('filing_date', sa.DateTime(), nullable=False),
    sa.Column('confirmation_date', sa.DateTime(), nullable=True),
    sa.Column('admin_confirmed', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['admin_confirmed'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wanted_type'], ['account_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arrangement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.Column('number_of_seats', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('guide', sa.Integer(), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.CheckConstraint('number_of_seats > 0', name='check_seats_number_positive'),
    sa.CheckConstraint('price > 0', name='check_price_positive'),
    sa.CheckConstraint('start_date < end_date', name='check_dates_correct'),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
    sa.ForeignKeyConstraint(['guide'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_type',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_type_id'], ['account_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'account_type_id')
    )
    op.create_table('reservation',
    sa.Column('customer', sa.Integer(), nullable=False),
    sa.Column('arrangement', sa.Integer(), nullable=False),
    sa.Column('seats_needed', sa.Integer(), nullable=False),
    sa.CheckConstraint('seats_needed >= 0', name='check_seats_positive'),
    sa.ForeignKeyConstraint(['arrangement'], ['arrangement.id'], ),
    sa.ForeignKeyConstraint(['customer'], ['user.id'], ),
    sa.PrimaryKeyConstraint('customer', 'arrangement')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('user_type')
    op.drop_table('arrangement')
    op.drop_table('account_type_change_request')
    op.drop_table('user')
    op.drop_table('account_type')
    # ### end Alembic commands ###
