"""init

Revision ID: 7ed293e58e15
Revises: 
Create Date: 2022-01-05 21:15:44.755396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed293e58e15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('seats_needed', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('arrangement_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('seats_needed >= 0', name='check_seats_positive'),
    sa.ForeignKeyConstraint(['arrangement_id'], ['arrangement.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'arrangement_id')
    )
    op.add_column('account_type_change_request', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('account_type_change_request', sa.Column('wanted_type_id', sa.Integer(), nullable=False))
    op.add_column('account_type_change_request', sa.Column('admin_confirmed_id', sa.Integer(), nullable=True))
    op.drop_constraint('account_type_change_request_wanted_type_fkey', 'account_type_change_request', type_='foreignkey')
    op.drop_constraint('account_type_change_request_admin_confirmed_fkey', 'account_type_change_request', type_='foreignkey')
    op.drop_constraint('account_type_change_request_user_fkey', 'account_type_change_request', type_='foreignkey')
    op.create_foreign_key(None, 'account_type_change_request', 'user', ['admin_confirmed_id'], ['id'])
    op.create_foreign_key(None, 'account_type_change_request', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'account_type_change_request', 'account_type', ['wanted_type_id'], ['id'])
    op.drop_column('account_type_change_request', 'wanted_type')
    op.drop_column('account_type_change_request', 'admin_confirmed')
    op.drop_column('account_type_change_request', 'user')
    op.add_column('arrangement', sa.Column('guide_id', sa.Integer(), nullable=True))
    op.add_column('arrangement', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.drop_constraint('arrangement_guide_fkey', 'arrangement', type_='foreignkey')
    op.drop_constraint('arrangement_creator_fkey', 'arrangement', type_='foreignkey')
    op.create_foreign_key(None, 'arrangement', 'user', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'arrangement', 'user', ['guide_id'], ['id'])
    op.drop_column('arrangement', 'guide')
    op.drop_column('arrangement', 'creator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arrangement', sa.Column('creator', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('arrangement', sa.Column('guide', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'arrangement', type_='foreignkey')
    op.drop_constraint(None, 'arrangement', type_='foreignkey')
    op.create_foreign_key('arrangement_creator_fkey', 'arrangement', 'user', ['creator'], ['id'])
    op.create_foreign_key('arrangement_guide_fkey', 'arrangement', 'user', ['guide'], ['id'])
    op.drop_column('arrangement', 'creator_id')
    op.drop_column('arrangement', 'guide_id')
    op.add_column('account_type_change_request', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('account_type_change_request', sa.Column('admin_confirmed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('account_type_change_request', sa.Column('wanted_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'account_type_change_request', type_='foreignkey')
    op.drop_constraint(None, 'account_type_change_request', type_='foreignkey')
    op.drop_constraint(None, 'account_type_change_request', type_='foreignkey')
    op.create_foreign_key('account_type_change_request_user_fkey', 'account_type_change_request', 'user', ['user'], ['id'])
    op.create_foreign_key('account_type_change_request_admin_confirmed_fkey', 'account_type_change_request', 'user', ['admin_confirmed'], ['id'])
    op.create_foreign_key('account_type_change_request_wanted_type_fkey', 'account_type_change_request', 'account_type', ['wanted_type'], ['id'])
    op.drop_column('account_type_change_request', 'admin_confirmed_id')
    op.drop_column('account_type_change_request', 'wanted_type_id')
    op.drop_column('account_type_change_request', 'user_id')
    op.drop_table('reservation')
    # ### end Alembic commands ###
